# Borrowed from https://github.com/lpan/dotfiles/blob/master/files/desktop/.zshrc
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Antigen
source ~/.antigen/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

# antigen theme eendroroy/alien alien
antigen theme robbyrussell
# antigen theme agnoster

# Tell antigen that you're done.
antigen apply

# Minimalist theme
# ZSH_THEME="powerlevel9k/powerlevel9k"
ZSH_THEME="robbyrussell"
# ZSH_THEME="alien"
#ZSH_THEME="agnoster"

# manually set your language environment
export LANG=en_US.UTF-8

DEFAULT_USER='aiden'

# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux


if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

bindkey -v

source $ZSH/oh-my-zsh.sh
source $HOME/.bash_aliases

# ls when directory changes
chpwd() ls

set -o vi
bindkey -M viins 'jk' vi-cmd-mode

function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/NORMAL}/(main|viins)/INSERT}"
    RPS2=$RPS1
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select



