# Borrowed from https://github.com/lpan/dotfiles/blob/master/files/desktop/.zshrc
# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# doesn't throw an error when wildcard isn't found
unsetopt nomatch

# Antigen
source ~/.antigen/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions

# antigen theme eendroroy/alien alien
antigen theme robbyrussell
# antigen theme agnoster

# Tell antigen that you're done.
antigen apply
ZSH_THEME="robbyrussell"

# manually set your language environment
export LANG=en_US.UTF-8

# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" ]] && exec tmux


if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ls when directory changes
chpwd() ls


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

autoload zmv
autoload zcp


